recipe: default.v1

language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 2
    max_ngram: 4
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 2
  - name: DIETClassifier
    epochs: 100
    random_seed: 42
    constrain_similarities: true
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7

policies:
  - name: AugmentedMemoizationPolicy
    max_history: 10
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 10
    epochs: 100
    constrain_similarities: true
assistant_id: 20240423-103323-concrete-cabinet
